// Code generated by "stringer -type=coil"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldResetLight-0]
	_ = x[fieldResetLightGreen-1]
	_ = x[red1R-2]
	_ = x[red1G-3]
	_ = x[red1B-4]
	_ = x[red2R-5]
	_ = x[red2G-6]
	_ = x[red2B-7]
	_ = x[blue1R-8]
	_ = x[blue1G-9]
	_ = x[blue1B-10]
	_ = x[blue2R-11]
	_ = x[blue2G-12]
	_ = x[blue2B-13]
	_ = x[matchReset-14]
	_ = x[stackLightGreen-15]
	_ = x[stackLightOrange-16]
	_ = x[stackLightRed-17]
	_ = x[stackLightBlue-18]
	_ = x[stackLightBuzzer-19]
	_ = x[heartbeat-20]
	_ = x[coilCount-21]
}

const _coil_name = "fieldResetLightfieldResetLightGreenred1Rred1Gred1Bred2Rred2Gred2Bblue1Rblue1Gblue1Bblue2Rblue2Gblue2BmatchResetstackLightGreenstackLightOrangestackLightRedstackLightBluestackLightBuzzerheartbeatcoilCount"

var _coil_index = [...]uint8{0, 15, 35, 40, 45, 50, 55, 60, 65, 71, 77, 83, 89, 95, 101, 111, 126, 142, 155, 169, 185, 194, 203}

func (i coil) String() string {
	if i < 0 || i >= coil(len(_coil_index)-1) {
		return "coil(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _coil_name[_coil_index[i]:_coil_index[i+1]]
}
